### ISSUE TITLE
Mainnet node sync fails

### ISSUE THREAD

**Issue by e00dan** [nervosnetwork/godwoken#565]
Using following config: https://github.com/Kuzirashi/nervos-godwoken-testnet-node/blob/master/mainnet/config/godwoken-readonly-config.toml

Other user and me we are getting errors:

"Hi, I have a similar problem with the godwoken node. With the help of Daniel and the new settings it managed to sync up to block 96956 and stalled there. 
I looked intto the console logs and saw no  indication of wat might be the problem. Then I restarted the godwoken docker container. Now it gives the following output, similar to yours:"
```
mainnet-godwoken-1  | [2022-01-22T07:56:09Z INFO  gw_mem_pool::pool] [mem-pool] restore mem block from timestamp 1642838163580
mainnet-godwoken-1  | thread 'main' panicked at 'assertion failed: (left == right)
mainnet-godwoken-1  |   left: H256([173, 27, 122, 85, 100, 199, 151, 160, 3, 86, 170, 123, 56, 172, 111, 55, 95, 105, 30, 223, 92, 89, 107, 161, 91, 204, 119, 117, 158, 254, 18, 145]),
mainnet-godwoken-1  |  right: H256([14, 93, 154, 44, 124, 30, 22, 196, 98, 164, 83, 11, 123, 101, 159, 180, 70, 15, 95, 34, 200, 113, 114, 175, 111, 245, 255, 238, 171, 217, 75, 14]): set new snapshot', crates/mem-pool/src/pool.rs:855:13
mainnet-godwoken-1  | stack backtrace:
mainnet-godwoken-1  |    0: rust_begin_unwind
mainnet-godwoken-1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
mainnet-godwoken-1  |    1: core::panicking::panic_fmt
mainnet-godwoken-1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
mainnet-godwoken-1  |    2: core::panicking::assert_failed_inner
mainnet-godwoken-1  |    3: core::panicking::assert_failed
mainnet-godwoken-1  |    4: gw_mem_pool::pool::MemPool::reset::{{closure}}
mainnet-godwoken-1  |    5: async_io::driver::block_on
mainnet-godwoken-1  |    6: gw_mem_pool::pool::MemPool::create
mainnet-godwoken-1  |    7: gw_block_producer:🏃:run
mainnet-godwoken-1  |    8: godwoken::main
mainnet-godwoken-1  | note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
```

---

DevRel node:
```
godwoken_1  |    8: godwoken::main
godwoken_1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
godwoken_1  | [2022-01-24T16:48:01Z INFO  gw_mem_pool::pool] Saving mem block to "./mem-pool/mem-block"
godwoken_1  | [2022-01-24T16:48:01Z INFO  gw_mem_pool::restore_manager] [mem-pool] save restore save mem block "./mem-pool/mem-block/mem_block_timestamp_1643042881360"
godwoken_1  | [2022-01-24T16:49:02Z INFO  gw_block_producer::runner] Runtime threads: 8. (set environment 'SMOL_THREADS' to tune this value)
godwoken_1  | [2022-01-24T16:49:04Z INFO  gw_mem_pool::pool] [mem-pool] restore mem block from timestamp 1643042881360
godwoken_1  | thread 'main' panicked at 'assertion failed: `(left == right)`
godwoken_1  |   left: `H256([16, 185, 232, 59, 98, 227, 24, 213, 107, 110, 113, 203, 223, 20, 60, 104, 183, 122, 31, 245, 27, 62, 234, 138, 229, 254, 132, 116, 182, 198, 123, 229])`,
godwoken_1  |  right: `H256([14, 93, 154, 44, 124, 30, 22, 196, 98, 164, 83, 11, 123, 101, 159, 180, 70, 15, 95, 34, 200, 113, 114, 175, 111, 245, 255, 238, 171, 217, 75, 14])`: set new snapshot', crates/mem-pool/src/pool.rs:855:13
godwoken_1  | stack backtrace:
godwoken_1  |    0: rust_begin_unwind
godwoken_1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
godwoken_1  |    1: core::panicking::panic_fmt
godwoken_1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
godwoken_1  |    2: core::panicking::assert_failed_inner
godwoken_1  |    3: core::panicking::assert_failed
godwoken_1  |    4: gw_mem_pool::pool::MemPool::reset::{{closure}}
godwoken_1  |    5: async_io::driver::block_on
godwoken_1  |    6: gw_mem_pool::pool::MemPool::create
godwoken_1  |    7: gw_block_producer::runner::run
godwoken_1  |    8: godwoken::main
godwoken_1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
godwoken_1  | [2022-01-24T16:49:04Z INFO  gw_mem_pool::pool] Saving mem block to "./mem-pool/mem-block"
godwoken_1  | [2022-01-24T16:49:04Z INFO  gw_mem_pool::restore_manager] [mem-pool] save restore save mem block "./mem-pool/mem-block/mem_block_timestamp_1643042944312"
godwoken_1  | [2022-01-24T16:50:05Z INFO  gw_block_producer::runner] Runtime threads: 8. (set environment 'SMOL_THREADS' to tune this value)
godwoken_1  | [2022-01-24T16:50:07Z INFO  gw_mem_pool::pool] [mem-pool] restore mem block from timestamp 1643042944312
godwoken_1  | thread 'main' panicked at 'assertion failed: `(left == right)`
godwoken_1  |   left: `H256([16, 185, 232, 59, 98, 227, 24, 213, 107, 110, 113, 203, 223, 20, 60, 104, 183, 122, 31, 245, 27, 62, 234, 138, 229, 254, 132, 116, 182, 198, 123, 229])`,
godwoken_1  |  right: `H256([14, 93, 154, 44, 124, 30, 22, 196, 98, 164, 83, 11, 123, 101, 159, 180, 70, 15, 95, 34, 200, 113, 114, 175, 111, 245, 255, 238, 171, 217, 75, 14])`: set new snapshot', crates/mem-pool/src/pool.rs:855:13
godwoken_1  | stack backtrace:
godwoken_1  |    0: rust_begin_unwind
godwoken_1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
godwoken_1  |    1: core::panicking::panic_fmt
godwoken_1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
godwoken_1  |    2: core::panicking::assert_failed_inner
godwoken_1  |    3: core::panicking::assert_failed
godwoken_1  |    4: gw_mem_pool::pool::MemPool::reset::{{closure}}
godwoken_1  |    5: async_io::driver::block_on
godwoken_1  |    6: gw_mem_pool::pool::MemPool::create
godwoken_1  |    7: gw_block_producer::runner::run
godwoken_1  |    8: godwoken::main
godwoken_1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
godwoken_1  | [2022-01-24T16:50:07Z INFO  gw_mem_pool::pool] Saving mem block to "./mem-pool/mem-block"
godwoken_1  | [2022-01-24T16:50:07Z INFO  gw_mem_pool::restore_manager] [mem-pool] save restore save mem block "./mem-pool/mem-block/mem_block_timestamp_1643043007338"
godwoken_1  | [2022-01-24T16:51:08Z INFO  gw_block_producer::runner] Runtime threads: 8. (set environment 'SMOL_THREADS' to tune this value)
godwoken_1  | [2022-01-24T16:51:10Z INFO  gw_mem_pool::pool] [mem-pool] restore mem block from timestamp 1643043007338
godwoken_1  | thread 'main' panicked at 'assertion failed: `(left == right)`
godwoken_1  |   left: `H256([16, 185, 232, 59, 98, 227, 24, 213, 107, 110, 113, 203, 223, 20, 60, 104, 183, 122, 31, 245, 27, 62, 234, 138, 229, 254, 132, 116, 182, 198, 123, 229])`,
godwoken_1  |  right: `H256([14, 93, 154, 44, 124, 30, 22, 196, 98, 164, 83, 11, 123, 101, 159, 180, 70, 15, 95, 34, 200, 113, 114, 175, 111, 245, 255, 238, 171, 217, 75, 14])`: set new snapshot', crates/mem-pool/src/pool.rs:855:13
godwoken_1  | stack backtrace:
godwoken_1  |    0: rust_begin_unwind
godwoken_1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
godwoken_1  |    1: core::panicking::panic_fmt
godwoken_1  |              at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
godwoken_1  |    2: core::panicking::assert_failed_inner
godwoken_1  |    3: core::panicking::assert_failed
godwoken_1  |    4: gw_mem_pool::pool::MemPool::reset::{{closure}}
godwoken_1  |    5: async_io::driver::block_on
godwoken_1  |    6: gw_mem_pool::pool::MemPool::create
godwoken_1  |    7: gw_block_producer::runner::run
godwoken_1  |    8: godwoken::main
godwoken_1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Related to: https://github.com/Kuzirashi/nervos-godwoken-testnet-node/issues/2

cc @jjyr @zeroqn

**Comment by jjyr** [comment]
https://github.com/Kuzirashi/nervos-godwoken-testnet-node/blob/master/mainnet/config/godwoken-readonly-config.toml#L77-L92

These three option should be empty array. Please resync the node.

**Comment by jjyr** [comment]
Please resync the node after fix the option.

**Comment by e00dan** [comment]
Turns out I had typo in config. I think we used allowed_polyjuice_contract_creator_address instead of allowed_polyjuice_contract_creator_account_ids. It's syncing now (already 38k blocks synced) after emptying arrays and fixing option name.
