### ISSUE TITLE
Execute 2 times ( destruct after create2) leads to exit2 

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken#964]
env: https://github.com/RetricSu/godwoken-kicker.git
branch: compatibility-changes
commit: 76430974cc0b8f88e2bca659725cb8664d3b78d2
solodity code
```
pragma solidity ^0.8.6;
import "hardhat/console.sol";

contract create2_test{

    Factory factory;
    FactoryAssembly factoryAssembly;
    event GasCost(uint256 gasCost);
    event DeployContract(uint256  idx,address deployAddress);
    constructor() public {
        factory = new Factory();
        factoryAssembly = new FactoryAssembly();
    }

    function testCreate() public returns(bool){
        bytes memory  codeBytes = factoryAssembly.getBytecode(msg.sender,1);
        address calculateAddress = factoryAssembly.getAddress(codeBytes,1);
        address deployAddress = factoryAssembly.deploy(codeBytes,1);
//        console.log(calculateAddress);
//        console.log(deployAddress);
        require(calculateAddress == deployAddress,"address is not eq");
        TestContract tc = TestContract(deployAddress);
        require(tc.getFoo() == 1,"foo must eq");
    }

//    function test_create2_destruct_creat2() public {
//        bytes memory  codeBytes = factoryAssembly.getBytecode(msg.sender,1);
//        address calculateAddress = factoryAssembly.getAddress(codeBytes,1);
//        address deployAddress = factoryAssembly.deploy(codeBytes,1);
//        require(calculateAddress == deployAddress,"address is not eq");
//        TestContract tc = TestContract(deployAddress);
//        tc.selfDestruct();
//        console.log("111");
//        deployAddress = factoryAssembly.deploy(codeBytes,1);
//        console.log("222");
//        require(calculateAddress == deployAddress,"address is not eq after selfDestruct");
//    }

    function test_create2_deploy_2_same_contract() public {
        bytes memory  codeBytes = factoryAssembly.getBytecode(msg.sender,1);
        address addr = factoryAssembly.deploy(codeBytes,12313123);
        emit DeployContract(1,addr);
        address addr2 = factoryAssembly.deploy(codeBytes,12313123);
        emit DeployContract(2,addr2);
        require(addr2 == address(0),"add2 eq 0x0");
    }



    function test_create2_destruct() public {
        bytes memory  codeBytes = factoryAssembly.getBytecode(msg.sender,1);
        address deployAddress = factoryAssembly.deploy(codeBytes,1312312313131);
        TestContract tc = TestContract(deployAddress);
        tc.selfDestruct();
        emit DeployContract(3,deployAddress);
        require(address(tc)!=address(0),"addr must not eq 0");
    }


    function test_create2_selfDestruct_create2() public {
        bytes memory  codeBytes = factoryAssembly.getBytecode(msg.sender,1);
        address deployAddress = factoryAssembly.deploy(codeBytes,13123123131312);
        TestContract tc = TestContract(deployAddress);
        tc.selfDestruct();
        address next_deployAddress = factoryAssembly.deploy(codeBytes,13123123131312);
//        console.log(tc.getFoo());
        require(next_deployAddress==address(0),"self destruct deploy will be 0x0");
    }

}

contract Factory {
    // Returns the address of the newly deployed contract
    function deploy(
        address _owner,
        uint _foo,
        bytes32 _salt
    ) public payable returns (address) {
        // This syntax is a newer way to invoke create2 without assembly, you just need to pass salt
        // https://docs.soliditylang.org/en/latest/control-structures.html#salted-contract-creations-create2
        return address(new TestContract{salt: _salt}(_owner, _foo));
    }
}

// This is the older way of doing it using assembly
contract FactoryAssembly {
    event Deployed(address addr, uint salt);

    // 1. Get bytecode of contract to be deployed
    // NOTE: _owner and _foo are arguments of the TestContract's constructor
    function getBytecode(address _owner, uint _foo) public pure returns (bytes memory) {
        bytes memory bytecode = type(TestContract).creationCode;

        return abi.encodePacked(bytecode, abi.encode(_owner, _foo));
    }

    // 2. Compute the address of the contract to be deployed
    // NOTE: _salt is a random number used to create an address
    function getAddress(bytes memory bytecode, uint _salt)
    public
    view
    returns (address)
    {
        bytes32 hash = keccak256(
            abi.encodePacked(bytes1(0xff), address(this), _salt, keccak256(bytecode))
        );

        // NOTE: cast last 20 bytes of hash to address
        return address(uint160(uint(hash)));
    }

    // 3. Deploy the contract
    // NOTE:
    // Check the event log Deployed which contains the address of the deployed TestContract.
    // The address in the log should equal the address computed from above.
    function deploy(bytes memory bytecode, uint _salt) public payable returns(address){
        address addr;

        /*
        NOTE: How to call create2

        create2(v, p, n, s)
        create new contract with code at memory p to p + n
        and send v wei
        and return the new address
        where new address = first 20 bytes of keccak256(0xff + address(this) + s + keccak256(mem[p…(p+n)))
              s = big-endian 256-bit value
        */
        assembly {
            addr := create2(
            callvalue(), // wei sent with current call
            // Actual code starts after skipping the first 32 bytes
            add(bytecode, 0x20),
            mload(bytecode), // Load the size of code contained in the first 32 bytes
            _salt // Salt from function arguments
            )


        }
//        console.log("deploy succ");
//        console.log(addr);
//        assembly{
//            if iszero(extcodesize(addr)) {
//                revert(0, 0)
//            }
//        }

        emit Deployed(addr, _salt);
        return addr;
    }
}

contract TestContract {
    address public owner;
    uint public foo = 3;
    event T(uint256 idx);
    constructor(address _owner, uint _foo) payable {
        owner = _owner;
        foo = _foo;
        emit  T(1);
    }

    function getFoo() public view returns(uint){
        return foo;
    }


    function getBalance() public view returns (uint) {
        return address(this).balance;
    }
    function selfDestruct() public {
        selfdestruct(payable(msg.sender));
    }
}
```

step:
1. deploy create2_test contract 
2. invoke test_create2_destruct
3. invoke test_create2_destruct

result:
1. deploy success
2. invoke success
3. invoke failed
hardhat log
```
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0xdf665b41c9de660f3f50983fc6b321cb3803c903e95e21b976664d996db81114", transaction={"hash":"0xdf665b41c9de660f3f50983fc6b321cb3803c903e95e21b976664d996db81114","type":0,"accessList":null,"blockHash":"0xda96dd225d61e5dfd2a7ae4bb9ad75a438201b7cdc4c021cb1a009922bcc4a58","blockNumber":2776,"transactionIndex":0,"confirmations":1,"from":"0x0000000000000000000000000000000000000000","gasPrice":{"type":"BigNumber","hex":"0x01"},"gasLimit":{"type":"BigNumber","hex":"0xf07f1c"},"to":null,"value":{"type":"BigNumber","hex":"0x00"},"nonce":0,"data":"0x","r":"0x0000000000000000000000000000000000000000000000000000000000000000","s":"0x0000000000000000000000000000000000000000000000000000000000000000","v":0,"creates":"0xBd770416a3345F91E4B34576cb804a576fa48EB1","chainId":0}, receipt={"to":null,"from":"0x0000000000000000000000000000000000000000","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0xf07f1c"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xda96dd225d61e5dfd2a7ae4bb9ad75a438201b7cdc4c021cb1a009922bcc4a58","transactionHash":"0xdf665b41c9de660f3f50983fc6b321cb3803c903e95e21b976664d996db81114","logs":[],"blockNumber":2776,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0xf07f1c"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.6.1)
     at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
     at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
     at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/base-provider.ts:1523:24)
     at step (node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
     at Object.next (node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
     at fulfilled (node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
godwoken-web3 log
```
[1] request.method: eth_estimateGas
[1] fromId: 9
[1] rawL2Transaction: {
[1]   "from_id": "0x9",
[1]   "to_id": "0x118",
[1]   "nonce": "0x0",
[1]   "args": "0xffffff504f4c590000000001000000000100000000000000000000000000000000000000000000000000000000000000040000004d290d3e"
[1] }
[1] Call gw rpc "gw_execute_raw_l2transaction" error: JSONRPCError: server error {"code":-32600,"message":"invalid exit code 2","data":{"tx_hash":"0xf87b15eb0536128c08e4a8f90379e35ceca8b027302393f7616040d4d3b326a9","block_number":"0xad8","return_data":"0x","last_log":{"account_id":"0x118","service_flag":"0x2","data":"0x4e20f800000000004e20f80000000000000000000000000000000000000000000000000002000000"},"exit_code":"0x2"}}
[1] POST / 200 102.559 ms - 45
[1] request.method: eth_gasPrice
[1] POST / 200 4.486 ms - 40
[1] request.method: eth_getTransactionCount
[1] POST / 200 19.451 ms - 41
[1] request.method: eth_sendRawTransaction
[1] sendRawTransaction gw hash: 0x85956e2120b8761b90e40ddd48d1ff50838fe2f95f16682e48a202b212f5350e
[1] sendRawTransaction eth hash: 0xdf665b41c9de660f3f50983fc6b321cb3803c903e95e21b976664d996db81114
[1] POST / 200 36.101 ms - 103
[1] request.method: eth_chainId
[1] POST / 200 0.873 ms - 50
[1] request.method: eth_getTransactionByHash
[1] POST / 200 9.434 ms - 39
[1] request.method: eth_chainId
[1] POST / 200 0.975 ms - 50
[1] request.method: eth_getTransactionByHash
[1] POST / 200 9.640 ms - 40
[1] request.method: eth_blockNumber
[1] request.method: eth_chainId
[1] POST / 200 1.509 ms - 51
[1] POST / 200 3.648 ms - 43
[1] request.method: eth_chainId
[1] POST / 200 0.736 ms - 51
[1] request.method: eth_getTransactionByHash
[1] POST / 200 10.194 ms - 534
[1] request.method: eth_chainId
[1] POST / 200 2.741 ms - 51
[1] request.method: eth_getTransactionReceipt
[1] POST / 200 9.938 ms - 1017
```
expected: 3 invoke success
### actions
local:https://github.com/gpBlockchain/gw-evm-opcode-test/runs/5748378802?check_suite_focus=true
godwoken:https://github.com/gpBlockchain/gw-evm-opcode-test/runs/5748477981
#### Reproduce the problem
fork https://github.com/gpBlockchain/gw-evm-opcode-test.git
exec actions
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/32102187/160753471-5451d56f-5513-4022-9782-184d7b5dc34e.png">

**Comment by Flouse** [comment]
> step:
> 
> 1. deploy create2_test contract
> 2. invoke test_create2_destruct
> 3. invoke test_create2_destruct

Step 2 and 3 use the same `_salt` to invoke create2, this results the same Polyjuice contract script.
While the [`selfdestruct` interface](https://github.com/nervosnetwork/godwoken-polyjuice/blob/compatibility-breaking-changes/c/polyjuice.h#L531-L571
) in Polyjuice only marks the account destructed, not deletes it really.
So, step 3 will fail to create a new Polyjuice contract account.

**Comment by jjyr** [comment]
不确定这里是否需要处理。 GW account 目前是不支持删除的。这种场景感觉也是以太坊上开发者会尽量避免的一个场景，因为 selfdestruct 后合约理应不再使用，但再次创建后 account 地址会一样？这时候用户使用是有风险的我理解。

感觉优先级不高，可以看下有无实际需要的场景

**Comment by Flouse** [comment]
context:

# CREATE2 Use Case for Crypto Exchange

> Contrary to a popular misconception, you can deploy a smart contract at the same address several times with CREATE2 opcode. This is because CREATE2 checks that the nonce of the target address is zero (it is set to one at the beginning of the constructor). In this case, the selfdestruct() function resets nonce of the address every time. Thus, if you call CREATE2 with the same arguments again, the check on nonce will pass.
https://blog.smartdec.net/how-to-define-smart-contract-address-before-the-deploy-create2-use-case-for-decentralized-exchange-52b7daa7873b
